image: ${CI_REGISTRY}/amethyst/amethyst-ci/base:latest

stages:
  - lint
  - check
  - test
  - build-docs
  - deploy-docs
  - invalidate-aws

before_script:
  # We need to make a copy of the script, in case we
  # checkout a branch somewhere that doesn't contain it
  - cp scripts/docs-ci-helper.bash scripts/.docs-ci-helper.bash
  - chmod +x scripts/.docs-ci-helper.bash

prepare:
  stage: .pre
  only:
    - move-ci-to-gitlab
  script:
    - cargo --version
    - rustc --version

    # Check if required deploy vars are set
    - if [[ -z "$TAG_STABLE" ]]; then echo "TAG_STABLE must be set!"; exit 1; fi;
    - if [[ -z "$BRANCH_WASM" ]]; then echo "BRANCH_WASM must be set!"; exit 1; fi;

    - if [[ -z "$DOCS_SERVER" ]]; then echo "DOCS_SERVER must be set!"; exit 1; fi;
    - if [[ -z "$DOCS_APP" ]]; then echo "DOCS_APP must be set!"; exit 1; fi;
    - if [[ -z "$BOOK_APP" ]]; then echo "BOOK_APP must be set!"; exit 1; fi;

lint:
  stage: lint
  variables:
    RUSTFLAGS: "-D warnings"
  script:
    - cargo fmt -- --check
    - cargo clippy --all --all-targets --features "vulkan sdl_controller json saveload tiles storage-event-control"

check-stable:
  image: ${CI_REGISTRY}/amethyst/amethyst-ci/builder-stable:latest
  stage: check
  variables:
    RUSTFLAGS: "-D warnings"
  script:
    - cargo update
    - cargo check --all --all-targets --features "vulkan sdl_controller json saveload tiles storage-event-control"

check-nightly:
  image: ${CI_REGISTRY}/amethyst/amethyst-ci/builder-nightly:latest
  stage: check
  variables:
    RUSTFLAGS: "-D warnings"
  script:
    - cargo update
    - cargo check --all --all-targets --features "vulkan sdl_controller json saveload tiles storage-event-control"

test-stable:
  image: ${CI_REGISTRY}/amethyst/amethyst-ci/builder-stable:latest
  stage: test
  script:
    # For the stable test, we're combining testing with coverage so
    # we don't have to run the tests twice
    - ./scripts/coverage.sh
    - curl -s https://codecov.io/bash | bash -s ./target/coverage/merged -t "$CODECOV_TOKEN"

# For the docs and book build, we output the built sites as artifacts and cache them.
# A file containing the revision hash is output into the directory, so we can check
# if we need to rebuild and redeploy. If we detect an existing cached version, we check
# the revision and rebuild appropriately.

# Additionally, we output the paths that were rebuilt into docs-paths-updated and
# book-paths-updated, so that we can later trigger invalidations in cloudfront for
# the relevant paths.

docs:
  image: ${CI_REGISTRY}/amethyst/amethyst-ci/builder-stable:latest
  stage: build-docs
  only:
    - move-ci-to-gitlab
  cache:
    key: docs-cache
    paths:
      - docs-public-master/
      - docs-public-stable/
      - docs-public-wasm/
  artifacts:
    paths:
      - docs-public-master/
      - docs-public-stable/
      - docs-public-wasm/
      - docs-paths-updated
  script:
    # Build stable, master and wasm docs
    - ./scripts/.docs-ci-helper.bash build docs master docs-public-master "/master/*"
    - ./scripts/.docs-ci-helper.bash build docs $TAG_STABLE docs-public-stable "/stable/*"
    # - ./scripts/.docs-ci-helper.bash build docs-wasm $BRANCH_WASM docs-public-wasm "/wasm/*"

book:
  image: ${CI_REGISTRY}/amethyst/amethyst-ci/mdbook:latest
  stage: build-docs
  only:
    - move-ci-to-gitlab
  cache:
    key: book-cache
    paths:
      - book-public-master/
      - book-public-stable/
      - book-public-wasm/
  artifacts:
    paths:
      - book-public-master/
      - book-public-stable/
      - book-public-wasm/
      - book-paths-updated
  script:
    # Build stable, master and wasm book
    - ./scripts/.docs-ci-helper.bash build book master book-public-master "/master/*"
    - ./scripts/.docs-ci-helper.bash build book $TAG_STABLE book-public-stable "/stable/*"
    # - ./scripts/.docs-ci-helper.bash build book $BRANCH_WASM book-public-wasm "/wasm/*"

deploy-docs:
  image: ${CI_REGISTRY}/amethyst/amethyst-ci/base:latest
  stage: deploy-docs
  only:
    - move-ci-to-gitlab
  dependencies:
    - docs
    - book
  script:
    # Add the key for dokku deployment and set permissions
    # See https://docs.gitlab.com/ee/ci/ssh_keys/
    - echo "Adding docs deploy SSH key..."
    - eval $(ssh-agent -s)
    - echo "$DOCS_SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh

    # These are the folders we'll package and deploy as tarballs
    - mkdir docs-public && mkdir book-public

    # Move our static files, mark the directory as the root directory
    # by creating .static and copy our custom nginx config
    - mv docs-public-stable docs-public/stable
    - mv docs-public-master docs-public/master
    # - mv docs-public-wasm docs-public/wasm
    - touch docs-public/.static
    - cp docs-nginx.conf.sigil docs-public/app-nginx.conf.sigil

    # Check if the index file contains the package name to validate the deployment
    - echo "/stable/amethyst/ amethyst" >> docs-public/CHECKS
    - echo "/master/amethyst/ amethyst" >> docs-public/CHECKS
    # - echo "/wasm/amethyst/ amethyst" >> docs-public/CHECKS

    # Check if the revision file contains the revisions we just deployed
    - echo "/master/.rev $(cat docs-public/master/.rev)" >> docs-public/CHECKS
    - echo "/stable/.rev $(cat docs-public/stable/.rev)" >> docs-public/CHECKS
    # - echo "/wasm/.rev $(cat docs-public/wasm/.rev)" >> docs-public/CHECKS

    # Move our static files, mark the directory as the root directory
    # by creating .static and copy our custom nginx config
    - mv book-public-stable book-public/stable
    - mv book-public-master book-public/master
    # - mv book-public-wasm book-public/wasm
    - touch book-public/.static
    - cp docs-nginx.conf.sigil book-public/app-nginx.conf.sigil

    # Check if the index file contains the package name to validate the deployment
    - echo "/stable/ Amethyst" >> book-public/CHECKS
    - echo "/master/ Amethyst" >> book-public/CHECKS
    # - echo "/wasm/ Amethyst" >> book-public/CHECKS

    # Check if the revision file contains the revisions we just deployed
    - echo "/master/.rev $(cat book-public/master/.rev)" >> book-public/CHECKS
    - echo "/stable/.rev $(cat book-public/stable/.rev)" >> book-public/CHECKS
    # - echo "/wasm/.rev $(cat book-public/wasm/.rev)" >> book-public/CHECKS

    # Deploy!
    - echo "Deploying docs..."
    - tar c docs-public | ssh -o StrictHostKeyChecking=no dokku@${DOCS_SERVER} tar:in ${DOCS_APP}

    - echo "Deploying book..."
    - tar c book-public | ssh -o StrictHostKeyChecking=no dokku@${DOCS_SERVER} tar:in ${BOOK_APP}

invalidate-aws:
  image: ${CI_REGISTRY}/amethyst/amethyst-ci/aws-cli:latest
  stage: invalidate-aws
  only:
    - move-ci-to-gitlab
  dependencies:
    - docs
    - book
    - deploy-docs
  script:
    # Create invalidations for changed paths
    - ./scripts/.docs-ci-helper.bash invalidate-aws